int form();                    //登录界面
int Gmima();                   //管理员登录验证
int Xmima();                   //学生登录验证
int sselect();                 //学生菜单
int mselect();                 //管理员主菜单
int query();                   //查询学生信息菜单
int statistic();               //数据管理（统计）菜单
int mmanage();                 //学生密码管理菜单
void refernumber();            //按学号查询某同学情况
void refernumber_class();      //按班级号查询所有同学、并按学号从小到大排列
void referclass();             //按照班级、以学生姓名拼音顺序排列
void refercourse();            //按某类课程，输出未达到要求的学生名单
void referstandard_meet();     //在满足毕业条件的学生中,按从高到低的分数列名单
void studentself();            //学生进行本人学分信息查询
void GmimaXG();                //管理员修改自己的密码
void XmimaXG();                //学生修改自己的密码
void querym_stdudent();        //查询指定学生的密码
void modifym_stdudent();       //修改指定学生的密码
void dataadd();                //添加数据
void data_modify();            //修改数据
void data_delete();            //删除数据